name: gaussian_splatting_cuda12
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - plyfile
  - python=3.10
  - pip=25.2
  - tqdm
  - pytorch>=2.1
  - pytorch-cuda=12.1
  - torchvision
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
